@startuml
!include common.puml
!include k8s/cm.puml
!include k8s/kubernetes.puml
!include k8s/pod.puml
!include k8s/pv.puml
!include k8s/pvc.puml
!include k8s/secret.puml
!include k8s/svc.puml
!include opentelemetry/opentelemetry.puml
!include opentelemetry/receiver.puml
!include opentelemetry/collector.puml
!include opentelemetry/exporter.puml
!include opentelemetry/processor.puml
!include grafana/tempo.puml
!include grafana/loki.puml
!include onepoint/legend.puml
!include <logos/grafana>


KUBERNETES("K8S","Kubernetes") {
    CM("CM", "Config map")
    POD("POD", "Pod")
    PV("PV", "Persistent volume")
    PVC("PVC", "Persistent volume claim")
    SECRET("SECRET", "Chhhhh")
    SVC("SVC", "Service")
}

OTLP("OTEL", "Opentelemetry"){
    RECEIVER("RC", "Receiver")
    COLLECTOR("CL", "Collector")
    EXPORTER("EXP", "Exporter")
    PROCESSOR("PROC", "Processor")
}

cloud <$grafana> {
    TEMPO(Tempo)
    LOKI(Loki)
}

LAYOUT_WITH_LEGEND()

@enduml
